# Generated by Django 3.2.3 on 2021-06-12 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('idDeporte', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Deporte')),
                ('nombreDeporte', models.CharField(max_length=50, verbose_name='Nombre del Deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Evento')),
                ('nombreEvento', models.CharField(max_length=50, verbose_name='Nombre del Evento')),
                ('fechaEvento', models.CharField(max_length=50, verbose_name='Fecha del Evento')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('runCliente', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Run')),
                ('nombreCliente', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidoPaterno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido Paterno')),
                ('apellidoMaterno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido Materno')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.deporte')),
            ],
        ),
    ]
